FROM nixos/nix:latest

RUN git config --global --add safe.directory /work

# Enable flakes + nix-command, disable sandbox (important in Docker)
RUN mkdir -p /etc/nix && \
    echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf && \
    echo "sandbox = false" >> /etc/nix/nix.conf

# Common flake dependencies
RUN nix profile add nixpkgs#jq

WORKDIR /work

