name: Nix Build Check

on:
  push:
    branches:
      - dev  # This triggers the workflow only when you push to the 'dev' branch
  pull_request:
    branches:
      - dev  # This will also trigger the workflow for PRs targeting the 'dev' branch

jobs:
  nix-build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.05

